### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by sstolzenberg** [masato-ogishi/Repitope#2]
Hello Masato,
great paper, great approach!
I would like to try Repitope, but ran into several installation issues on either my Mac or Linux with different R versions (either devtools or e.g. "Biostring" dependent packages "not available" for particular R versions > 3.0).
On which R version, and operating systems have you developed Repitope?
Thanks!
Sebastian

**Comment by masato-ogishi** [comment]
Sorry for the delay! I developed this package on Windows R 3.5.0. But I checked that it should work under macOS too. I didn't check but I guess Ubuntu would also be fine. 
You should install the devtools package at first from CRAN. Then you should install "msa" from BioConductor. https://bioconductor.org/packages/release/bioc/html/msa.html
It is strange but currently Bioconductor is an independent source of package so you should install msa manually. All other Bioconductor dependencies will be installed. Finally, you can install Repitope. Note that you need rJava setup beforehand. Otherwise the core extraTree machine learning algorithm cannot be run!
